#pragma once

#include <stdbool.h>

#define EMCUETITI_CONFIG_DEBUG				true
#define EMCUETITI_CONFIG_MAXCLIENTS			4
#define EMCUETITI_CONFIG_MAXSUBSPERCLIENT	4
#define EMCUETITI_CONFIG_CLIENTBUFFERSZ		64
